// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Amplify = require("../utils/Amplify.bs.js");
var GatsbyLink = require("gatsby-link-reason/src/GatsbyLink.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("IndexPage");

console.log(Amplify.configure);

function text(prim) {
  return prim;
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Hi People"), React.createElement("p", undefined, "Welcome to your new Gatsby site."), React.createElement("p", undefined, "Welcome to your new Gatsby site with multi-user authentication powered by", React.createElement("a", {
                                  href: "https://amplify.aws"
                                }, "AWS Amplify")), React.createElement("p", undefined, "Create a new account: ", ReasonReact.element(undefined, undefined, GatsbyLink.make("/app/signup", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Sign Up"]))), ReasonReact.element(undefined, undefined, GatsbyLink.make("/app/login", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Sign In"])), React.createElement("br", undefined), ReasonReact.element(undefined, undefined, GatsbyLink.make("/app/home", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Home"])), React.createElement("br", undefined), ReasonReact.element(undefined, undefined, GatsbyLink.make("/app/profile", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Your Profile"])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

exports.component = component;
exports.text = text;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
