// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var GatsbyLink = require("gatsby-link-reason/src/GatsbyLink.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Auth = require("../utils/auth");
var Router = require("@reach/router");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Lib = require("@aws-amplify/auth/lib");

var container = {
  background: "rebeccapurple",
  marginBottom: "1.45rem"
};

var headerContainer = {
  margin: "0 auto",
  maxWidth: "960px",
  padding: "1.45rem 1.0875rem"
};

var headerTitle = {
  color: "white",
  textDecoration: "none"
};

var link = {
  color: "white",
  cursor: "pointer",
  textDecoration: "underline"
};

var Styles = /* module */[
  /* container */container,
  /* headerContainer */headerContainer,
  /* headerTitle */headerTitle,
  /* link */link
];

var component = ReasonReact.statelessComponent("Header");

function make(siteTitle, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var callback;
              try {
                callback = (function (param) {
                    Router.navigate("/app/login");
                    return /* () */0;
                  });
              }
              catch (raw_exn){
                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                if (exn[0] === Js_exn.$$Error) {
                  var e = exn[1];
                  callback = (function (param) {
                      console.log("error", e);
                      return /* () */0;
                    });
                } else {
                  throw exn;
                }
              }
              var match = Auth.isLoggedIn();
              return React.createElement("div", {
                          style: container
                        }, React.createElement("div", {
                              style: headerContainer
                            }, React.createElement("h1", {
                                  style: {
                                    margin: "0"
                                  }
                                }, ReasonReact.element(undefined, undefined, GatsbyLink.make("/", undefined, Caml_option.some(headerTitle), undefined, undefined, undefined, undefined, undefined, undefined, /* array */[siteTitle]))), match ? React.createElement("p", {
                                    style: link,
                                    onClick: (function (_event) {
                                        Lib.default.signOut();
                                        Auth.logout(callback);
                                        return /* () */0;
                                      })
                                  }, "SignOut") : null));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.siteTitle, /* array */[]);
      }));

exports.Styles = Styles;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
