// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var AwsExportsJs = require("../aws-exports.js");
var Lib = require("@aws-amplify/auth/lib");

var configure = Lib.default.configure(AwsExportsJs.default);

exports.configure = configure;
/* configure Not a pure module */
